# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

#### Entering th release zone
pages:
    stage: deploy
    tags: [qlf-ci.inria.fr]
    only:
    - tags
    script:
    - pip install tox
    - tox -e docs
    - mkdir -p public/
    - cp -r docs/_build/html/* public/
    artifacts:
      paths:
      - public

pypi:
    stage: deploy
    tags: [qlf-ci.inria.fr]
    only:
    - tags
    script:
    - python setup.py bdist_wheel
    - pip install twine
    # credentials are set in the env by gitlab
    - twine upload dist/* --verbose
